### ISSUE TITLE
Linux Mint installation error

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#1]
Hi. I receive this error when trying to install totalsize on Linux Mint with Python 3.6.9 installed:

`Could not find a version that satisfies the requirement totalsize (from versions: ) 
No matching distribution found for totalsize
`

**Comment by theychx** [comment]
Is `pip3 install totalsize` working?

**Comment by beskhu3epnm** [comment]
Yes. The pip3 install did work.

I have another question. I wish to download the total file-size of all videos from a very large channel with 55K videos. totalsize does not appear to support the --continue option? It is likely my computer will freeze-lock in attempting to record the stats from that many videos, and there is no option to resume a partially finished trawl.

I am also interested in pulling the total duration of all videos from the same channel, but suffered freeze-locks when I used youtube-dl, and as far as I can tell, the --continue option does not work with recording textual stats.

**Comment by theychx** [comment]
> Yes. The pip3 install did work.

Cool.
> It is likely my computer will freeze-lock in attempting to record the stats from that many videos

I'm pretty sure it won't.
> I am also interested in pulling the total duration of all videos from the same channel

Please create a new issue with this feature request.
