### ISSUE TITLE
Parsing the filesize

### ISSUE THREAD

**Issue by anonieee** [theychx/totalsize#16]
Is there any way to output only the total filesize as an integer? Preferably in bytes. I'm using cmd.

**Comment by theychx** [comment]
The csv output option, `-c`, uses bytes for filesizes. I can add a "bytes" option for the regular output as well, if that is useful.

**Comment by anonieee** [comment]
Yeah, but can you also make an option to exclusively output the total filesize. That would be very useful for scripting.
Maybe add an option to output only the total media files as integer too.
Something like this:

```
C:\>totalsize --size https://www.youtube.com/playlist?list=xxxx
85454

C:\>totalsize --media https://www.youtube.com/playlist?list=xxxx
15
```

**Comment by theychx** [comment]
Ah, I misread your question. Yes, I can do that.

**Comment by anonieee** [comment]
Thank you!

**Comment by anonieee** [comment]
Another thing: maybe make the options modular so that you can output both options at once (with the total media files printed before the total size):
```
C:\>totalsize --size --media https://www.youtube.com/playlist?list=xxxx
15
85454
C:\>
```
Thanks again!

**Comment by theychx** [comment]
@anonieee `0.4.0` is out! Please test it.

**Comment by anonieee** [comment]
Thank you and sorry for the late reply!
