### ISSUE TITLE
Retry per media

### ISSUE THREAD

**Issue by anonieee** [theychx/totalsize#19]
Currently once it exceeds the max retry, the program exits. Can you make an option so that it just skips to the next video in the playlist instead?

**Comment by theychx** [comment]
That's an oversight on my part. Current behaviour doesn't really make sense. I'll fix it ASAP.

**Comment by archiif** [comment]
Thank you!

**Comment by anonieee** [comment]
Thank you!

**Comment by theychx** [comment]
`0.4.1` is out!
