### ISSUE TITLE
Blank output for channel shorthand

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#28]
I'm given a [blank output](https://files.catbox.moe/vocath.txt) when using -m on this channel: [https://www.youtube.com/fredrikknudsen](https://www.youtube.com/fredrikknudsen)
It's likely to do with the absence of a channel or user preceding the account name. The URL shorthand doesn't work, but the long version does work: [https://www.youtube.com/channel/UCbWcXB0PoqOsAvAdfzWMf0w](https://www.youtube.com/channel/UCbWcXB0PoqOsAvAdfzWMf0w)

I'm not sure what qualifies a YouTube channel to this shorthand, I guess if they have a huge amount of watch time or subscribers or something.

**Comment by theychx** [comment]
It looks as though `youtube-dl` thinks you mean https://www.youtube.com/user/fredrikknudsen, which has nothing to do with https://www.youtube.com/channel/UCbWcXB0PoqOsAvAdfzWMf0w. Not much I can do about that I'm afraid.
