### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by leodomi** [theychx/totalsize#31]
The script doesn't work anymore

**Comment by theychx** [comment]
Works fine here. Care to elaborate?

**Comment by leodomi** [comment]
Yeah sorry about the lack of information in my first comment.

I tried to use it like I used it few month go, but it doesn't work for me. 

Here is a screenshot of my cmd : 
I tried with a channel, then a playlist and a playlist with " "

![image](https://user-images.githubusercontent.com/33042520/99465244-3c36d300-293a-11eb-9698-b7561d16d275.png)

The line `'list' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.` can be translated into `'list' is not recognized as an internal command.
or external, an executable program or a command file.`

Maybe I'm using it wrong but I don't see where.

**Comment by theychx** [comment]
Try putting the URL in quotes.

**Comment by leodomi** [comment]
I did it in the last try in the picture, but it says `Error: Resource not found`

**Comment by tempo550** [comment]
I believe YouTube made some changes and Totalsize needs to be updated again. @theychx

**Comment by theychx** [comment]
The communication with YouTube is handled by `yt-dlp`
Try:
```
pip3 install -U yt-dlp
```

**Comment by tempo550** [comment]
Yes, it's not gathering any data. The data fields are empty.
