### ISSUE TITLE
totalsize feature suggestions

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#8]
I have some feature request suggestions. I don't know if these are too ambitious or stray too far from what this script already does.

- List the video duration, and total them
- List the views, and total them
- List the like/dislike ratio (maybe with a percentage), and total them
- List the amount of comments, and total them
- Provide option to order the list by max/min, date invert, alphabetical
- Provide option to continue if process is ended

**Comment by theychx** [comment]
> List the video duration, and total them
> List the views, and total them
> List the like/dislike ratio (maybe with a percentage), and total them

Should be doable.
> List the amount of comments, and total them

The youtube-dl source specifies a couple of comments related optional fields, but the youtube extractor does not seem to use those. So I'm not going to bother.
> Provide option to order the list by max/min, date invert, alphabetical

Definitely out of scope.
> Provide option to continue if process is ended

Totalsize would have to keep track of intermediate data itself, so not keen on implementing that. Youtube-dl has the ability to process only a subset of a playlist (cli options `--playlist-start` and `--playlist-end`). Totalsize could pass those on to youtube-dl, if that is helpful.

**Comment by beskhu3epnm** [comment]
Very nice! Thank you for adding many of my feature requests in the latest release. I'm excited to run this script again on many channels. I'll inform you if there are problems.

**Comment by beskhu3epnm** [comment]
I wish there was a feature to sort the output in order of total duration, total file size, total views, total likes, et cetera. I don't know if this is challenging.

Video 1     1:18:40
Video 2     1:02:07
Video 3     0:43:46
Video 4     0:29:24
Video 5     0:12:51

**Comment by theychx** [comment]
You can use the csv option, and then sort the data in your preferred spreadsheet app.
