### ISSUE TITLE
Channels with hidden videos

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#9]
I have an odd request perhaps not strictly related to Totalsize. But let me see what you make of it. When YouTube Red was introduced in 2015, every channel was forced to agree to the new ToS changes. Channels that did not agree had all their videos hidden. The videos still exist, but not visible on the channel navigation page, don't show up in search, and can not be played. However, the basic information such as the thumbnails, titles, views, and I think the descriptions and comments are still visible if you have the video URL.

When I used Totalsize to pull the file sizes of a channel with hidden videos, to no surprise it output errors. However, the video titles showed up! This was a great asset as the channel has been hidden for years. When I attempted to pull info using youtube-dl however, it did not output anything.

My question is: why is it (do you think) that Totalsize can print the video titles during an error but youtube-dl doesn't? Do you have suggestions for how to pull information from channels with hidden videos? For reference, [here is a channel with 402 hidden videos](https://www.youtube.com/channel/UCf07Sn6WFGp2e47roPSMkng), and [here is one known video URL from that channel](https://www.youtube.com/watch?v=FD9KsE3tE_4).

**Comment by theychx** [comment]
> My question is: why is it (do you think) that Totalsize can print the video titles during an error but youtube-dl doesn't?

That's just the behaviour of the youtube-dl cli. It errs when a video is not available to you, which makes sense, given it's main purpose. Totalsize uses the same info but prints the title regardless.
In these cases, the only other data available to totalsize is the video id.
> Do you have suggestions for how to pull information from channels with hidden videos?

To do this you would need to circumvent the restriction on the videos. So for "It is not available in your country" you would have to use a proxy/VPN.
